### PR TITLE
Implement not dynamic delegate for ConfigureScope #511

### PR DESCRIPTION
**Pull request by Maxmystere**
Here is my PR for implementing the use of DECLARE_DELEGATE_OneParam for ConfigureScope #511

Converting FConfigureScopeDelegate to a non dynamic delegate might cause issues on migration of code for existing cpp users as now the cpp version of the implementation would be `FConfigureScopeDynDelegate` (but maybe could be good to make aware for people to replace their existing cpp code to use `FConfigureScopeDelegate`

### CODE REVIEW

**Comment by bitsandfoxes** [comment]
Thanks for contributing and sorry for the delay, we'll get back to you as soon as possible.

**Comment by Maxmystere** [comment]
Thanks for the reply, I got busy with other tasks so I didn't get the time to test it on mobile platforms but it should be ready for tests

**Comment by tustanivsky** [comment]
@Maxmystere I've run some tests for this on my side and everything works perfectly. The only thing I'd like to suggest is to rename the newly added non-dynamic delegate to `FConfigureScopeNativeDelegate` instead of changing the existing dynamic one - it should allow us to avoid breaking things for those who are using the plugin's API in C++.

**Comment by Maxmystere** [comment]
Thanks for the tests ! I've updated with what you asked, makes the review a bit bigger but yeah it's cleaner for people updating

**Comment by tustanivsky** [comment]
> Thanks for the tests ! I've updated with what you asked, makes the review a bit bigger but yeah it's cleaner for people updating

Great! I'll give it another go and get back to you.

**Review by tustanivsky — APPROVED** [review]

**Pull request merged**
