### PR TITLE
Fixing Staging problem

### LINKED ISSUE #205: Unable to copy CrashPad_Handler.exe when staging on a different machine
### Environment

How do you use Sentry?
Sentry.io

Which version of the SDK?
Latest from Main

How did you install the package? (Git-URL, Assetstore)
Git

Which version of Unreal?
5.1

Is this happening in Unreal (editor) or on a player like Android, iOS, Windows?
Build Farm

### Steps to Reproduce

1. Compile Editor
2. Compile Client
3. Cook (On a different agent, using the artifacts from the first jobs)
4: Attempt to stage (On the same agent as the cook) 

### Expected Result

No errors

### Actual Result
Skip copying file E:\Horde\Work\Inc\Sync\Redacted\Plugins\External\SentryUnrealPlugin\Binaries\Win64\crashpad_handler.exe because it doesn't exist.
ERROR: Failed to copy E:\Horde\Work\Inc\Sync\Redacted\Plugins\External\SentryUnrealPlugin\Binaries\Win64\crashpad_handler.exe to E:\Horde\Work\Inc\Sync\Redacted\Saved\StagedBuilds\WindowsClient\Trident\Plugins\External\SentryUnrealPlugin\Binaries\Win64\crashpad_handler.exe

### PR DESCRIPTION
**Pull request by Edstub207**
Closes #205

### CODE REVIEW

**Comment by Edstub207** [comment]
@tustanivsky I think I've hit this problem in other places as well, I'm not sure if you want to do this in a better way?

**Comment by tustanivsky** [comment]
> @tustanivsky I think I've hit this problem in other places as well, I'm not sure if you want to do this in a better way?

Don't we need to make similar changes for `sentry.dll` and `sentry.pdb` as well?

Also, I was wondering why the `crashpad_hadler.exe` couldn't be found if it is copied to the plugin's `Binaries` folder right before  adding the corresponding runtime dependency

**Comment by tustanivsky** [comment]
I recall we've switched to using `RuntimeDependencies.Add(Dest, Src)` instead of copying plugin dependencies manually a while ago however it turned out that this approach wasn't working properly so I've rolled back these changes. This [conversation](https://github.com/getsentry/sentry-unreal/issues/188#issuecomment-1383613427) should provide extra context

**Comment by Edstub207** [comment]
> I recall we've switched to using `RuntimeDependencies.Add(Dest, Src)` instead of copying plugin dependencies manually a while ago however it turned out that this approach wasn't working properly so I've rolled back these changes. This [conversation](https://github.com/getsentry/sentry-unreal/issues/188#issuecomment-1383613427) should provide extra context

👍 I have verified the latest version of this change works, when staging WindowsServer, WindowsClient and Linux Server.

**Comment by tustanivsky** [comment]
A similar fix can be found in #211. The only difference there is that `RuntimeDependencies.Add` calls stayed at their old place in order to keep binaries copying and actual dependencies management separate. Also, I had some concerns about whether it is safe to add runtime dependency only if the corresponding binary wasn't copied to the `Binaries` folder earlier.

**Pull request closed without merging**
